// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package imsdb

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
)

type EventAccessMode string

const (
	EventAccessModeRead        EventAccessMode = "read"
	EventAccessModeWrite       EventAccessMode = "write"
	EventAccessModeReport      EventAccessMode = "report"
	EventAccessModeWriteVisits EventAccessMode = "write_visits"
)

func (e *EventAccessMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EventAccessMode(s)
	case string:
		*e = EventAccessMode(s)
	default:
		return fmt.Errorf("unsupported scan type for EventAccessMode: %T", src)
	}
	return nil
}

type NullEventAccessMode struct {
	EventAccessMode EventAccessMode
	Valid           bool // Valid is true if EventAccessMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEventAccessMode) Scan(value interface{}) error {
	if value == nil {
		ns.EventAccessMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EventAccessMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEventAccessMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EventAccessMode), nil
}

func (e EventAccessMode) Valid() bool {
	switch e {
	case EventAccessModeRead,
		EventAccessModeWrite,
		EventAccessModeReport,
		EventAccessModeWriteVisits:
		return true
	}
	return false
}

func AllEventAccessModeValues() []EventAccessMode {
	return []EventAccessMode{
		EventAccessModeRead,
		EventAccessModeWrite,
		EventAccessModeReport,
		EventAccessModeWriteVisits,
	}
}

type EventAccessValidity string

const (
	EventAccessValidityAlways EventAccessValidity = "always"
	EventAccessValidityOnsite EventAccessValidity = "onsite"
)

func (e *EventAccessValidity) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EventAccessValidity(s)
	case string:
		*e = EventAccessValidity(s)
	default:
		return fmt.Errorf("unsupported scan type for EventAccessValidity: %T", src)
	}
	return nil
}

type NullEventAccessValidity struct {
	EventAccessValidity EventAccessValidity
	Valid               bool // Valid is true if EventAccessValidity is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEventAccessValidity) Scan(value interface{}) error {
	if value == nil {
		ns.EventAccessValidity, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EventAccessValidity.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEventAccessValidity) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EventAccessValidity), nil
}

func (e EventAccessValidity) Valid() bool {
	switch e {
	case EventAccessValidityAlways,
		EventAccessValidityOnsite:
		return true
	}
	return false
}

func AllEventAccessValidityValues() []EventAccessValidity {
	return []EventAccessValidity{
		EventAccessValidityAlways,
		EventAccessValidityOnsite,
	}
}

type IncidentState string

const (
	IncidentStateNew        IncidentState = "new"
	IncidentStateOnHold     IncidentState = "on_hold"
	IncidentStateDispatched IncidentState = "dispatched"
	IncidentStateOnScene    IncidentState = "on_scene"
	IncidentStateClosed     IncidentState = "closed"
)

func (e *IncidentState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IncidentState(s)
	case string:
		*e = IncidentState(s)
	default:
		return fmt.Errorf("unsupported scan type for IncidentState: %T", src)
	}
	return nil
}

type NullIncidentState struct {
	IncidentState IncidentState
	Valid         bool // Valid is true if IncidentState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIncidentState) Scan(value interface{}) error {
	if value == nil {
		ns.IncidentState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IncidentState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIncidentState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IncidentState), nil
}

func (e IncidentState) Valid() bool {
	switch e {
	case IncidentStateNew,
		IncidentStateOnHold,
		IncidentStateDispatched,
		IncidentStateOnScene,
		IncidentStateClosed:
		return true
	}
	return false
}

func AllIncidentStateValues() []IncidentState {
	return []IncidentState{
		IncidentStateNew,
		IncidentStateOnHold,
		IncidentStateDispatched,
		IncidentStateOnScene,
		IncidentStateClosed,
	}
}

type PlaceType string

const (
	PlaceTypeCamp  PlaceType = "camp"
	PlaceTypeArt   PlaceType = "art"
	PlaceTypeOther PlaceType = "other"
	PlaceTypeMv    PlaceType = "mv"
)

func (e *PlaceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PlaceType(s)
	case string:
		*e = PlaceType(s)
	default:
		return fmt.Errorf("unsupported scan type for PlaceType: %T", src)
	}
	return nil
}

type NullPlaceType struct {
	PlaceType PlaceType
	Valid     bool // Valid is true if PlaceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlaceType) Scan(value interface{}) error {
	if value == nil {
		ns.PlaceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PlaceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlaceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PlaceType), nil
}

func (e PlaceType) Valid() bool {
	switch e {
	case PlaceTypeCamp,
		PlaceTypeArt,
		PlaceTypeOther,
		PlaceTypeMv:
		return true
	}
	return false
}

func AllPlaceTypeValues() []PlaceType {
	return []PlaceType{
		PlaceTypeCamp,
		PlaceTypeArt,
		PlaceTypeOther,
		PlaceTypeMv,
	}
}

type ActionLog struct {
	ID             int64
	CreatedAt      float64
	ActionType     string
	Method         sql.NullString
	Path           sql.NullString
	Referrer       sql.NullString
	UserID         sql.NullInt64
	UserName       sql.NullString
	PositionID     sql.NullInt64
	PositionName   sql.NullString
	ClientAddress  sql.NullString
	HttpStatus     sql.NullInt16
	DurationMicros sql.NullInt64
}

type Event struct {
	ID          int32
	Name        string
	IsGroup     bool
	ParentGroup sql.NullInt32
}

type EventAccess struct {
	ID         int32
	Event      int32
	Expression string
	Mode       EventAccessMode
	Validity   EventAccessValidity
	Expires    sql.NullFloat64
}

type FieldReport struct {
	Event          int32
	Number         int32
	Created        float64
	Summary        sql.NullString
	IncidentNumber sql.NullInt32
}

type FieldReportReportEntry struct {
	Event             int32
	FieldReportNumber int32
	ReportEntry       int32
}

type Incident struct {
	Event               int32
	Number              int32
	Created             float64
	Priority            int8
	State               IncidentState
	Started             float64
	Closed              sql.NullFloat64
	Summary             sql.NullString
	LocationName        sql.NullString
	LocationAddress     sql.NullString
	LocationDescription sql.NullString
}

type IncidentIncidentType struct {
	Event          int32
	IncidentNumber int32
	IncidentType   int32
}

type IncidentLinkedIncident struct {
	Event1          int32
	IncidentNumber1 int32
	Event2          int32
	IncidentNumber2 int32
}

type IncidentRanger struct {
	ID             int32
	Event          int32
	IncidentNumber int32
	RangerHandle   string
	Role           sql.NullString
}

type IncidentReportEntry struct {
	Event          int32
	IncidentNumber int32
	ReportEntry    int32
}

type IncidentType struct {
	ID          int32
	Name        string
	Hidden      bool
	Description sql.NullString
}

type Place struct {
	Event          int32
	Type           PlaceType
	Number         int32
	Name           string
	LocationString string
	ExternalData   json.RawMessage
}

type ReportEntry struct {
	ID                       int32
	Author                   string
	Text                     string
	Created                  float64
	Generated                bool
	Stricken                 bool
	AttachedFile             sql.NullString
	AttachedFileOriginalName sql.NullString
	AttachedFileMediaType    sql.NullString
}

type SchemaInfo struct {
	Version int16
}

type Visit struct {
	Event                int32
	Number               int32
	Created              float64
	IncidentNumber       sql.NullInt32
	GuestPreferredName   sql.NullString
	GuestLegalName       sql.NullString
	GuestDescription     sql.NullString
	GuestActionPlan      sql.NullString
	GuestCampName        sql.NullString
	GuestCampAddress     sql.NullString
	GuestCampDescription sql.NullString
	GuestCampContacts    sql.NullString
	ArrivalTime          sql.NullFloat64
	ArrivalMethod        sql.NullString
	ArrivalState         sql.NullString
	ArrivalReason        sql.NullString
	ArrivalBelongings    sql.NullString
	DepartureTime        sql.NullFloat64
	DepartureMethod      sql.NullString
	DepartureState       sql.NullString
	ResourceSitter       sql.NullString
	ResourceBedID        sql.NullString
	ResourceRest         sql.NullString
	ResourceClothes      sql.NullString
	ResourcePogs         sql.NullString
	ResourceFoodBev      sql.NullString
	ResourceOther        sql.NullString
}

type VisitRanger struct {
	ID           int32
	Event        int32
	VisitNumber  int32
	RangerHandle string
	Role         sql.NullString
}

type VisitReportEntry struct {
	Event       int32
	VisitNumber int32
	ReportEntry int32
}
