// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package imsdb

import (
	"context"
)

type Querier interface {
	ActionLogs(ctx context.Context, db DBTX, arg ActionLogsParams) ([]ActionLogsRow, error)
	AddActionLog(ctx context.Context, db DBTX, arg AddActionLogParams) (int64, error)
	AddEventAccess(ctx context.Context, db DBTX, arg AddEventAccessParams) (int64, error)
	AttachFieldReportToIncident(ctx context.Context, db DBTX, arg AttachFieldReportToIncidentParams) error
	AttachIncidentTypeToIncident(ctx context.Context, db DBTX, arg AttachIncidentTypeToIncidentParams) error
	AttachRangerHandleToIncident(ctx context.Context, db DBTX, arg AttachRangerHandleToIncidentParams) error
	AttachRangerToVisit(ctx context.Context, db DBTX, arg AttachRangerToVisitParams) error
	AttachReportEntryToFieldReport(ctx context.Context, db DBTX, arg AttachReportEntryToFieldReportParams) error
	AttachReportEntryToIncident(ctx context.Context, db DBTX, arg AttachReportEntryToIncidentParams) error
	AttachReportEntryToVisit(ctx context.Context, db DBTX, arg AttachReportEntryToVisitParams) error
	AttachVisitToIncident(ctx context.Context, db DBTX, arg AttachVisitToIncidentParams) error
	ClearEventAccessForExpression(ctx context.Context, db DBTX, arg ClearEventAccessForExpressionParams) error
	ClearEventAccessForMode(ctx context.Context, db DBTX, arg ClearEventAccessForModeParams) error
	CreateEvent(ctx context.Context, db DBTX, arg CreateEventParams) (int64, error)
	CreateFieldReport(ctx context.Context, db DBTX, arg CreateFieldReportParams) error
	CreateIncident(ctx context.Context, db DBTX, arg CreateIncidentParams) (int64, error)
	CreateIncidentType(ctx context.Context, db DBTX, arg CreateIncidentTypeParams) (int64, error)
	CreatePlace(ctx context.Context, db DBTX, arg CreatePlaceParams) error
	CreateReportEntry(ctx context.Context, db DBTX, arg CreateReportEntryParams) (int64, error)
	CreateVisit(ctx context.Context, db DBTX, arg CreateVisitParams) (int64, error)
	DetachIncidentTypeFromIncident(ctx context.Context, db DBTX, arg DetachIncidentTypeFromIncidentParams) error
	DetachRangerFromVisit(ctx context.Context, db DBTX, arg DetachRangerFromVisitParams) error
	DetachRangerHandleFromIncident(ctx context.Context, db DBTX, arg DetachRangerHandleFromIncidentParams) error
	Event(ctx context.Context, db DBTX, id int32) (EventRow, error)
	EventAccessAll(ctx context.Context, db DBTX) ([]EventAccessAllRow, error)
	// This returns access for a target event, as well as for that event's
	// parent group, if any. If the target event *is* a group, this query
	// will return nothing. That's intentional, and it helps prevent people
	// from adding incidents or FRs to event groups as though those were events.
	EventAndParentAccess(ctx context.Context, db DBTX, arg EventAndParentAccessParams) ([]EventAndParentAccessRow, error)
	Events(ctx context.Context, db DBTX) ([]EventsRow, error)
	FieldReport(ctx context.Context, db DBTX, arg FieldReportParams) (FieldReportRow, error)
	FieldReport_ReportEntries(ctx context.Context, db DBTX, arg FieldReport_ReportEntriesParams) ([]FieldReport_ReportEntriesRow, error)
	FieldReports(ctx context.Context, db DBTX, event int32) ([]FieldReportsRow, error)
	FieldReports_ReportEntries(ctx context.Context, db DBTX, arg FieldReports_ReportEntriesParams) ([]FieldReports_ReportEntriesRow, error)
	Incident(ctx context.Context, db DBTX, arg IncidentParams) (IncidentRow, error)
	IncidentType(ctx context.Context, db DBTX, id int32) (IncidentTypeRow, error)
	IncidentTypes(ctx context.Context, db DBTX) ([]IncidentTypesRow, error)
	Incident_LinkedIncidents(ctx context.Context, db DBTX, arg Incident_LinkedIncidentsParams) ([]Incident_LinkedIncidentsRow, error)
	Incident_Rangers(ctx context.Context, db DBTX, arg Incident_RangersParams) ([]Incident_RangersRow, error)
	Incident_ReportEntries(ctx context.Context, db DBTX, arg Incident_ReportEntriesParams) ([]Incident_ReportEntriesRow, error)
	Incidents(ctx context.Context, db DBTX, event int32) ([]IncidentsRow, error)
	Incidents_Rangers(ctx context.Context, db DBTX, event int32) ([]Incidents_RangersRow, error)
	Incidents_ReportEntries(ctx context.Context, db DBTX, arg Incidents_ReportEntriesParams) ([]Incidents_ReportEntriesRow, error)
	LinkIncidents(ctx context.Context, db DBTX, arg LinkIncidentsParams) error
	// This doesn't use "MAX" because sqlc can't figure out the type for aggregations :(.
	NextFieldReportNumber(ctx context.Context, db DBTX, event int32) (int32, error)
	// This doesn't use "MAX" because sqlc can't figure out the type for aggregations :(.
	NextIncidentNumber(ctx context.Context, db DBTX, event int32) (int32, error)
	// This doesn't use "MAX" because sqlc can't figure out the type for aggregations :(.
	NextVisitNumber(ctx context.Context, db DBTX, event int32) (int32, error)
	Places(ctx context.Context, db DBTX, arg PlacesParams) ([]PlacesRow, error)
	QueryEventID(ctx context.Context, db DBTX, name string) (QueryEventIDRow, error)
	RemovePlaces(ctx context.Context, db DBTX, arg RemovePlacesParams) error
	SchemaVersion(ctx context.Context, db DBTX) (int16, error)
	SetFieldReportReportEntryStricken(ctx context.Context, db DBTX, arg SetFieldReportReportEntryStrickenParams) error
	//
	// The "stricken" queries seem bloated at first blush, because the whole
	// "where ID in (..." could just be "where ID =". What it's doing though is
	// ensuring that the provided eventID and incidentNumber actually align with
	// the reportEntryID in question, and that's important for authorization purposes.
	//
	SetIncidentReportEntryStricken(ctx context.Context, db DBTX, arg SetIncidentReportEntryStrickenParams) error
	SetVisitReportEntryStricken(ctx context.Context, db DBTX, arg SetVisitReportEntryStrickenParams) error
	UnlinkIncidents(ctx context.Context, db DBTX, arg UnlinkIncidentsParams) error
	UpdateEvent(ctx context.Context, db DBTX, arg UpdateEventParams) error
	UpdateFieldReport(ctx context.Context, db DBTX, arg UpdateFieldReportParams) error
	UpdateIncident(ctx context.Context, db DBTX, arg UpdateIncidentParams) error
	UpdateIncidentType(ctx context.Context, db DBTX, arg UpdateIncidentTypeParams) error
	UpdateVisit(ctx context.Context, db DBTX, arg UpdateVisitParams) error
	Visit(ctx context.Context, db DBTX, arg VisitParams) (VisitRow, error)
	Visit_Rangers(ctx context.Context, db DBTX, arg Visit_RangersParams) ([]Visit_RangersRow, error)
	Visit_ReportEntries(ctx context.Context, db DBTX, arg Visit_ReportEntriesParams) ([]Visit_ReportEntriesRow, error)
	Visits(ctx context.Context, db DBTX, event int32) ([]VisitsRow, error)
	Visits_Rangers(ctx context.Context, db DBTX, event int32) ([]Visits_RangersRow, error)
	Visits_ReportEntries(ctx context.Context, db DBTX, arg Visits_ReportEntriesParams) ([]Visits_ReportEntriesRow, error)
}

var _ Querier = (*Queries)(nil)
