//
// See the file COPYRIGHT for copyright information.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Shared helpers for the Vitest tests in this directory.

import { readFileSync } from "node:fs";
import { join } from "node:path";
import process from "node:process";
import { vi } from "vitest";

// Replace the current document with a templ-rendered HTML fixture from the
// fixtures directory (generated by bin/rendertestfixtures, via `npm test`).
//
// Page modules look up their elements and run their init function at module
// import time, so tests must call this BEFORE dynamically importing the page
// module under test.
export function loadFixture(name: string): void {
    const html = readFileSync(join(process.cwd(), "web", "typescripttest", "fixtures", name), "utf8");
    document.open();
    document.write(html);
    document.close();
}

// Make a JSON Response like the IMS API would return. fetchNoThrow only
// parses the body when the content-type is exactly "application/json".
export function jsonResponse(body: unknown, status: number = 200): Response {
    return new Response(JSON.stringify(body), {
        status: status,
        headers: { "content-type": "application/json" },
    });
}

// Make an "application/problem+json" error Response, as returned by the
// server's herr package.
export function problemResponse(detail: string, status: number): Response {
    return new Response(JSON.stringify({ detail: detail, status: status }), {
        status: status,
        headers: { "content-type": "application/problem+json" },
    });
}

export type FetchHandler = (url: string, init?: RequestInit) => Response | undefined;

// Replace global fetch with a route handler, returning the mock function so
// that tests can inspect calls. Returning undefined from the handler rejects
// the fetch, which surfaces in fetchNoThrow's err result.
export function mockFetch(handler: FetchHandler) {
    const mock = vi.fn(async (url: string, init?: RequestInit): Promise<Response> => {
        const response = handler(url, init);
        if (response == null) {
            throw new Error(`no mocked fetch route for ${url}`);
        }
        return response;
    });
    vi.stubGlobal("fetch", mock);
    return mock;
}

type FlatpickrHook = (selectedDates: Date[], dateStr: string, instance: MockFlatpickr) => void;

interface FlatpickrOptionsLike {
    altFormat?: string;
    onReady?: FlatpickrHook;
    onChange?: FlatpickrHook;
    onClose?: FlatpickrHook;
}

// A minimal stand-in for the flatpickr date picker, which production pages
// load as a classic script. It mirrors the parts of the Flatpickr interface
// that ims.ts uses: altInput creation, _flatpickr on the input element,
// setDate, and the onReady/onChange hooks. setup.ts installs the factory as
// the flatpickr global; tests can inspect MockFlatpickr.instances and call
// setDate(date, true) to simulate the user picking a date.
export class MockFlatpickr {
    static instances: MockFlatpickr[] = [];

    config: FlatpickrOptionsLike;
    selectedDates: Date[] = [];
    input: HTMLInputElement;
    altInput: HTMLInputElement;

    constructor(selector: string | Node, opts: FlatpickrOptionsLike) {
        this.config = opts;
        const input = typeof selector === "string" ? document.querySelector(selector) : selector;
        if (!(input instanceof HTMLInputElement)) {
            throw new Error(`no input element for flatpickr selector ${selector}`);
        }
        this.input = input;
        this.altInput = document.createElement("input");
        this.input.insertAdjacentElement("afterend", this.altInput);
        (this.input as HTMLInputElement & { _flatpickr: MockFlatpickr })._flatpickr = this;
        opts.onReady?.([], "", this);
        MockFlatpickr.instances.push(this);
    }

    setDate(date: Date | string | Date[], triggerChange: boolean, _format?: string): void {
        const first = Array.isArray(date) ? date[0]! : date;
        const parsed = first instanceof Date ? first : new Date(first);
        this.selectedDates = [parsed];
        this.altInput.value = parsed.toISOString();
        if (triggerChange) {
            this.config.onChange?.(this.selectedDates, this.altInput.value, this);
        }
    }

    parseDate(date: string | number, _format: string): Date {
        return new Date(date);
    }
}

// A minimal stand-in for EventSource, which happy-dom doesn't implement.
// setup.ts installs this as the EventSource global; tests can inspect
// MockEventSource.instances and dispatch MessageEvents at them.
export class MockEventSource extends EventTarget {
    static instances: MockEventSource[] = [];

    static readonly CONNECTING = 0;
    static readonly OPEN = 1;
    static readonly CLOSED = 2;

    url: string;
    withCredentials: boolean;
    readyState: number = MockEventSource.CONNECTING;

    constructor(url: string, init?: { withCredentials?: boolean }) {
        super();
        this.url = url;
        this.withCredentials = init?.withCredentials ?? false;
        MockEventSource.instances.push(this);
    }

    close(): void {
        this.readyState = MockEventSource.CLOSED;
    }
}
