//
// See the file COPYRIGHT for copyright information.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package herr

import "time"

// Problem is an RFC9457 Problem instance.
// https://www.rfc-editor.org/rfc/rfc9457.html#appendix-A
type Problem struct {
	// Type is a URI reference that identifies the problem type
	Type string `json:"type"`
	// Title is a short, human-readable summary of the problem type.
	Title string `json:"title,omitzero"`
	// Status is the HTTP status code generated by the origin server for this occurrence
	// of the problem.
	Status int `json:"status"`
	// Detail is a human-readable explanation specific to this occurrence of the problem.
	Detail string `json:"detail,omitzero"`
	// Instance is a URI reference that identifies the specific occurrence of the problem.
	// It may or may not yield further information if dereferenced.
	Instance string `json:"instance"`

	//
	// Extensions - https://www.rfc-editor.org/rfc/rfc9457.html#section-3.2
	//

	// Timestamp is the time at which the Problem was created.
	Timestamp time.Time `json:"timestamp"`
}
