-- +goose Up
ALTER TABLE INCIDENT
    ADD COLUMN CREATED_BY integer,
    ADD CONSTRAINT `INCIDENT_CREATED_BY_TO_PERSON` FOREIGN KEY (CREATED_BY) REFERENCES PERSON(ID);

ALTER TABLE REPORT
    ADD COLUMN CREATED_BY integer,
    ADD CONSTRAINT `REPORT_CREATED_BY_TO_PERSON` FOREIGN KEY (CREATED_BY) REFERENCES PERSON(ID);

-- +goose Down
ALTER TABLE INCIDENT
    DROP FOREIGN KEY `INCIDENT_CREATED_BY_TO_PERSON`,
    DROP COLUMN CREATED_BY;

ALTER TABLE REPORT
    DROP FOREIGN KEY `REPORT_CREATED_BY_TO_PERSON`,
    DROP COLUMN CREATED_BY;
